Repository Step3-kakao-tech-campus/Team18_FE, pull requests merged in 2023-10, with the labels that each got.

#21 멘토님 Review PR 기반 코드 수정
  package.json
  src/Router.jsx
  src/components/common/Dropdown.jsx
  src/main.jsx
  tailwind.config.cjs
Labels: Priority: Normal, Status: Completed

#11 전남대_18조_Garden_4주차
  .eslintrc.json
  .github/ISSUE_TEMPLATE/default-template.md
  .github/ISSUE_TEMPLATE/discussion-template.md
  .github/pull_request_template.md
  .gitignore
  .prettierrc.json
  README.md
  index.html
  package-lock.json
  package.json
  postcss.config.cjs
  public/vite.svg
  src/App.css
  src/App.jsx
  src/apis/.gitkeep
  src/assets/react.svg
  src/components/account/.gitkeep
  src/components/chatting/.gitkeep
  src/components/common/Button.jsx
  src/components/common/Dropdown.jsx
  src/components/common/Tag.jsx
  src/components/mentoring/.gitkeep
  src/components/watching/.gitkeep
  src/hooks/.gitkeep
  src/hooks/useOutSideRef.js
  src/index.css
  src/layouts/.gitkeep
  src/layouts/AuthCheck.jsx
  src/layouts/Layout.jsx
  src/main.jsx
  src/pages/account/.gitkeep
  src/pages/chatting/.gitkeep
  src/pages/mentoring/.gitkeep
  src/pages/mentoring/Dashboard.jsx
  src/pages/mentoring/Edit.jsx
  src/pages/mentoring/Post.jsx
  src/pages/mentoring/Posts.jsx
  src/pages/mentoring/Write.jsx
  src/pages/watching/.gitkeep
  src/reset.css
  src/store/.gitkeep
  src/tests/.gitkeep
  src/utils/.gitkeep
  step3.md
  tailwind.config.cjs
  vite.config.js
Labels: Request Review

#48 사용자 정보 관리
  src/Router.jsx
  src/apis/user.js
  src/components/account/hooks/useLogin.js
  src/components/account/mockUser.js
  src/components/account/organisms/LoginForm.jsx
  src/components/account/organisms/SignupForm.jsx
  src/layouts/AuthCheck.jsx
  src/layouts/GNB.jsx
  src/layouts/navStructure.js
  src/pages/account/InformationPage.jsx
  src/pages/account/InterestPage.jsx
  src/pages/account/ProfilePage.jsx
  src/store/index.js
Labels: Type: Improvement, Priority: Normal, Status: Completed

#47 채널 리스트 기능 구현
  package-lock.json
  package.json
  src/Router.jsx
  src/apis/chatting/talkplus.js
  src/components/chatting/ChattingLeft.jsx
  src/components/chatting/CreateChannelModal.jsx
  src/components/chatting/channelList/ChannelListItem.jsx
  src/components/chatting/channelList/JoinedChannelList.jsx
  src/components/chatting/channelList/PublicChannelList.jsx
  src/components/chatting/channelList/Tabs.jsx
  src/components/chatting/channelRoom/ChatWrap.jsx
  src/components/chatting/channelRoom/MessageInput.jsx
  src/components/chatting/channelRoom/MessageList.jsx
  src/components/chatting/channelRoom/ReceivedMessage.jsx
  src/components/chatting/channelRoom/SentMessage.jsx
  src/components/chatting/talkplus/ChatWrap.jsx
  src/components/chatting/talkplus/MessageInput.jsx
  src/components/chatting/talkplus/MessageList.jsx
  src/components/chatting/talkplus/PublicChannelList.jsx
  src/components/chatting/talkplus/ReceivedMessage.jsx
  src/components/chatting/talkplus/SentMessage.jsx
  src/components/chatting/talkplus/UserBox.jsx
  src/constants/chatting/chatting.js
  src/pages/chatting/ChattingListPage.jsx
  src/pages/chatting/ChattingRoomsPage.jsx
  src/store/chatting/chatting.js
  src/utils/date.js
  tailwind.config.cjs
Labels: Type: Feature, Priority: Normal, Status: Completed
