Repository Step3-kakao-tech-campus/Team18_FE, pull requests merged in 2023-11, with the labels that each got.

#58 채팅 페이지 세부기능 구현
  src/apis/chatting/talkplus.js
  src/components/chatting/channelList/ChannelListItem.jsx
  src/components/chatting/channelList/JoinedChannelList.jsx
  src/components/chatting/channelList/PublicChannelList.jsx
  src/components/chatting/channelList/SearchInput.jsx
  src/components/chatting/channelRoom/ChatWrap.jsx
  src/components/chatting/channelRoom/MessageList.jsx
  src/components/chatting/channelRoom/ReceivedMessage.jsx
  src/components/chatting/channelRoom/SentMessage.jsx
  src/components/chatting/channelRoom/channelSetting/ChannelEditForm.jsx
  src/components/chatting/channelRoom/channelSetting/ChannelInfo.jsx
  src/components/chatting/channelRoom/channelSetting/ChannelSetting.jsx
  src/components/chatting/channelRoom/channelSetting/ChannelSettingItemBox.jsx
  src/components/chatting/modal/ChannelDetailModal.jsx
  src/components/chatting/modal/CreateChannelModal.jsx
  src/pages/chatting/ChattingListPage.jsx
  src/pages/chatting/ChattingRoomsPage.jsx
  src/store/chatting/chatting.js
Labels: Type: Feature, Priority: Normal

#61 채팅 세부기능 구현
  src/apis/chatting/talkplus.js
  src/components/chatting/channelList/PublicChannelList.jsx
  src/components/chatting/channelList/SearchInput.jsx
  src/constants/chatting/errorCode.js
  src/hooks/useDebounce.js
Labels: Type: Feature, Priority: Normal, Status: Completed

#62 Videos page 구현
  package-lock.json
  package.json
  src/Router.jsx
  src/apis/watching/mockVideo.js
  src/apis/watching/videos.js
  src/components/account/hooks/useLogin.js
  src/components/watching/.gitkeep
  src/components/watching/atoms/Card.jsx
  src/components/watching/atoms/Grid.jsx
  src/components/watching/atoms/Image.jsx
  src/components/watching/atoms/Skeleton.jsx
  src/components/watching/atoms/Video.jsx
  src/components/watching/molecules/VideoCard.jsx
  src/components/watching/organisms/SideVideoForm.jsx
  src/components/watching/organisms/VideoDetailForm.jsx
  src/components/watching/organisms/VideoGrid.jsx
  src/components/watching/templates/UserVideoList.jsx
  src/components/watching/templates/VideoDetailtemplate.jsx
  src/components/watching/templates/VideoList.jsx
  src/components/watching/utils/categoryId.js
  src/layouts/AuthCheck.jsx
  src/layouts/GNB.jsx
  src/layouts/Layout.jsx
  src/layouts/navStructure.js
  src/pages/watching/.gitkeep
  src/pages/watching/VideoDetailPage.jsx
  src/pages/watching/VideoListPage.jsx
Labels: Type: Feature, Priority: Normal, Status: In Progress

#74 채팅 세부 기능 구현
  package.json
  public/images/user_0.png
  src/Router.jsx
  src/apis/chatting/talkplus.js
  src/apis/mypage.js
  src/components/account/atoms/Error.jsx
  src/components/chatting/channelList/JoinedChannelList.jsx
  src/components/chatting/channelList/PublicChannelList.jsx
  src/components/chatting/channelList/Tabs.jsx
  src/components/chatting/channelRoom/MessageList.jsx
  src/components/chatting/channelRoom/ReceivedMessage.jsx
  src/components/chatting/channelRoom/channelSetting/ChannelInfo.jsx
  src/components/chatting/modal/ChannelDetailModal.jsx
  src/components/chatting/modal/CreateChannelModal.jsx
  src/components/chatting/skeleton/ChannelListItemSkeleton.jsx
  src/components/chatting/skeleton/ChannelListItemSkeletons.jsx
  src/hooks/useTalkLogin.js
  src/pages/chatting/ChattingListPage.jsx
  src/pages/chatting/ChattingRoomsPage.jsx
  src/store/chatting/chatting.js
Labels: Type: Feature, Type: Improvement, Priority: Normal, Status: Completed

#81 채팅 모달창 위에 뜨는 문제 해결
  src/components/chatting/channelList/PublicChannelList.jsx
  src/components/chatting/modal/ChannelDetailModal.jsx
  src/components/chatting/modal/CreateChannelModal.jsx
Labels: Type: Bug, Priority: Urgent, Status: Completed
